Update nodejs-ci.yml

diff --git a/.github/workflows/nodejs-ci.yml b/.github/workflows/nodejs-ci.yml
--- a/.github/workflows/nodejs-ci.yml
+++ b/.github/workflows/nodejs-ci.yml
@@ -92,11 +92,52 @@ jobs:
         run: |
           docker push ${{ secrets.DOCKER_HUB_USERNAME }}/todo-node-app-ci:latest
   
-      - name: Upload build artifacts (optional)
-        uses: actions/upload-artifact@v4
+  deploy:
+    name: Deploy Application (Docker Run)
+    runs-on: ubuntu-latest
+    needs: build
+  
+    env:
+      IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/todo-node-app-ci:latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
         with:
-          name: docker-image-info
-          path: ./Dockerfile
-          retention-days: 7
+          repository: Amitabh-DevOps/Project-03-Jenkins-CI-CD-Project-Todo-node-app
+          ref: master
+  
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+  
+      - name: Build Docker image
+        run: docker build -t $IMAGE_NAME .
+  
+      - name: Run container
+        run: |
+          docker run -d --name todo-app -p 8000:8000 $IMAGE_NAME
+          echo "Container started on port 8000"
+  
+      - name: Test container health
+        run: |
+          for i in {1..10}; do
+            if curl -fsS http://localhost:8000; then
+              echo "App is up!"
+              exit 0
+            fi
+            echo "Waiting for container..."
+            sleep 3
+          done
+          echo "App failed to start!"
+          docker logs todo-app
+          exit 1
+  
+      - name: Show container logs (always)
+        if: always()
+        run: docker logs todo-app
+  
+      - name: Stop container (always)
+        if: always()
+        run: docker rm -f todo-app
+
 
   
